### ISSUE TITLE
Add logical CSS classes to components, in order to facilitate deeper branding customization.

### ISSUE THREAD

**Issue by MrJoy** [avo-hq/avo#1976]
### Feature

Our branding just does not work with the limited options provided by Avo.  Of course, expanding the options you expose for this in enough granularity to be meaningful would be incredibly complex and high-effort so that's probably not a great idea.

But.

If you were to add logical class names to components.  E.G. `primary-button`, `resource-title`, `actions-list-button`, `delete-button`, etc then we could much more easily achieve what we want to achieve.

### Current workarounds

Some very very very gnarly CSS selectors have gotten me moooost of the way there, although I'm quite certain this is fragile and will either produce unexpected / undesirable results in situations I haven't yet run into or will break as you make changes down the road:

```css
/* Sidebar -------------------------------------------------------------------------------------- */

/* Background: */
.avo-sidebar { background-color: #434F54 !important; }

/* Links/text: */
.avo-sidebar *,
div[data-controller='menu'] div[data-menu-target='items'] a { color: #fff !important; }
div[data-controller='menu'] div[data-menu-target='items'] a.active { background-color: #ACB9BE !important; }
div[data-controller='menu'] div[data-menu-target='items'] a:hover { background-color: #ACB9BE !important; }

/* Section titles, icons, chevrons: */
div[data-controller='menu'] div[data-action='click->menu#triggerCollapse'],
div[data-controller='menu'] div[data-action='click->menu#triggerCollapse'] * {
  color: #ACB9BE !important;
}


/* Main Content Area ---------------------------------------------------------------------------- */

/* Page title/text: */
.content * { color: #434F54 !important; }

/* Page links: */
.content * a { color: #1091AE !important; }


/* Panel Area ----------------------------------------------------------------------------------- */

/* Text: */
.content *[data-target='panel-body'] :not(.button-component) *:not(a, svg, path, button *) { color: #434F54 !important; }

/* Links: */
.content * *[data-target='panel-body'] * a { color: #1091AE !important; }

/* Boolean false: */
.content * *[data-target='panel-body'] * svg.text-red-500 path { color: #E63946 !important; }

/* Boolean true: */
.content * *[data-target='panel-body'] * svg.text-green-600 path { color: #5ACD7A !important; }

/* Resource controls: */
.content * *[data-target='panel-body'] * *[data-control='resource-controls'] * svg * { color: #1091AE !important; }


/* Widgets -------------------------------------------------------------------------------------- */

/* Checkboxes: */
input[type='checkbox'] {
  background-color: #EEF2F3 !important;
  border-color: #ACB9BE !important;
}
input[type='checkbox']:checked { background-color: #434F54 !important; }

/* Primary Button: */
a.button-component.bg-primary-500 {
  background-color: #434F54 !important;
  border-color: #434F54 !important;
}
a.button-component.bg-primary-500 * { color: #FFF !important; }

/* Secondary Button: */
button.button-component:not([data-control='destroy']) {
  background-color: #fff !important;
  border-color: #ACB9BE !important;
}

button.button-component.border-primary-500,
button.button-component * { color: #434F54 !important; }

/* Dangerous Action: */
a.button-component.text-red-500 * { color: #E63946 !important; }

/* Action menu items: */
* *[data-target='actions-list'] a,
* *[data-target='actions-list'] * { color: #1091AE !important; }
* *[data-target='actions-list'] a:hover { background-color: rgb(241 242 243 / var(--tw-bg-opacity)) !important; }
```
