### ISSUE TITLE
Grid view: hide or customize poster image

### ISSUE THREAD

**Issue by sedubois** [avo-hq/avo#2347]
### Feature
The [grid view](https://docs.avohq.io/3.0/grid-view.html#custom-style) allows to customize the CSS for the title and body, but not for the poster image itself. It results in an "avocado" picture being repeated on each and every grid item. An option to hide this default cover picture would be welcome. Additionally, the cover picture could be configured with custom CSS like for the grid element title and body. 

### Current workarounds
None known.

### Screenshots or screen recordings
![Screenshot 2024-01-09 at 11 46 31](https://github.com/avo-hq/avo/assets/4217871/8db99d4f-b2bc-41d7-a517-d67a83308d9e)

**Comment by adrianthedev** [comment]
### Approach

I think it's not too difficult to retrofit this to the current DSL.

```ruby
self.grid_view = {
  card: -> do
    {
      title: record.name
    }
  end
}
```

If the returned object does not have the `cover_url` key, it will be omitted. the `.key? :cover_url` method can be used.

**Comment by goamaral** [comment]
Hello, I am creating a Pull request to implement this but there is an undocumented workaround. The cover wrapper class and style can be customized. So you can hide the cover wrapper in this cases.

```
    html: -> do
      {
        cover: {
          index: {
            wrapper: {
              classes: "hidden"
            }
          }
        }
      }
    end
```

**Comment by Paul-Bob** [comment]
Playing with it a bit and testing @goamaral suggestion I end up with this solution:

```ruby
self.grid_view = {
    card: -> do
      {
        cover_url:
          if record.cover_photo.attached?
            main_app.url_for(record.cover_photo.url)
          end,
        title: record.name,
        body: helpers.extract_excerpt(record.body)
      }
    end,
    html: -> do
      {
        cover: {
          index: {
            wrapper: {
              classes: record.cover_photo.attached? ? "" : "hidden"
            }
          }
        }
      }
    end
  }
```

![image](https://github.com/avo-hq/avo/assets/69730720/291674da-948a-4e5f-b335-538ffa02221a)

**Comment by adrianthedev** [comment]
One can use these CSS rules to hide the image, collapse the container, and still keep the checkbox in view.

```css
/* remove the `[data-resource-name="posts"]` selector to have that applied globally on every resource */
/* change `posts` to a different resource that you need */
[data-component-name="avo/index/grid_item_component"][data-resource-name="posts"] > div:first-child {
  /* we need to override the pb-3/4 class */
  padding-bottom: 36px !important;
}

[data-component-name="avo/index/grid_item_component"][data-resource-name="posts"] > div:first-child > a {
  /* hide the link and image */
  display: none;
}
```

![CleanShot 2024-02-05 at 16 03 27](https://github.com/avo-hq/avo/assets/1334409/99289f5c-c6d6-4164-ad7c-3cfe8c95adbf)
