### ISSUE TITLE
Customize the save button label for each resource

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#2594]
### Feature

Each resource should have the save button label customizable using I18n localization.

Ex:
```yml
---
en:
  avo:
    resource_translations:
      user:
        save: "Save user"
```

![image](https://github.com/avo-hq/avo/assets/69730720/ddb44ce1-6f64-41dc-b636-5a0aed2b64d7)

### Approach
Inside `lib/avo/resources/controls/save_button.rb` we should first try to fetch the label from `avo.resource_translations.#{resource.name}.save` and if not found fallback to `avo.save`

We can use the `default` option:

`I18n.t("avo.resource_translations.#{resource.name}.save", default: I18n.t("avo.save"))`
