### ISSUE TITLE
Show trix / rhino always_show variation

### ISSUE THREAD

**Issue by pjmuller** [avo-hq/avo#3263]
### Feature
Show a part of the content with a click to see more
See loom: https://www.loom.com/share/d95cfc272bb84e1797870265c9a710fb

to be discussed how we introduce this without creating regressions for users  that really want to hide everything.
introduce an extra boolean? `partial_show` ?

### Current workarounds
Define a custom partial for the show action -> copying the app/components/avo/fields/trix_field/show_component.html.erb and using our own styles?

or overwriting the `hidden` CSS class within this wrapper?

**Comment by pjmuller** [comment]
FYI: we 80/20 fixed this withi this css, #sharing-is-caring ;)
This works for both trix as rhino

```css
.trix-content.hidden {
  display: block !important;
}

.trix-content.hidden {
  clip-path: inset(0 0 calc(100% - 50px) 0);
  -webkit-mask-image: linear-gradient(to bottom, black 30px, transparent 50px);
  mask-image: linear-gradient(to bottom, black 30px, transparent 50px);
  max-height: 50px;
  min-height: 0px;
}

.trix-content:not(.hidden) {
  clip-path: none;
  -webkit-mask-image: none;
  mask-image: none;
}

a[data-action="click->hidden-input#showContent"].hidden {
  display: none !important;
}
```
