### ISSUE TITLE
Failed to clear Avo HQ response: Could not find table 'solid_cache_entries'

### ISSUE THREAD

**Issue by adrienpoly** [avo-hq/avo#3358]
### Describe the bug

I ran into an issue when trying to deploy an app for the first time with Kamal. 
At the end of the deploy script it failed with the message 
```
Failed to clear Avo HQ response: Could not find table 'solid_cache_entries'
```

I could reproduce it locally by simply running the command `rails db:prepare`

I suppose it is linked to the multi db configuration I have on my app (primary db + cache db + queue db)

```yml
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  timeout: 5000

# DATABASE CONFIGURATIONS
primary: &primary
  <<: *default
  database: storage/<%= Rails.env %>_rubyvideo.sqlite3

cache: &cache
  <<: *default
  migrations_paths: db/cache_migrate
  database: storage/<%= Rails.env %>-cache.sqlite3

queue: &queue
  <<: *default
  migrations_paths: db/queue_migrate
  database: storage/<%= Rails.env %>-queue.sqlite3

development:
  primary: *primary
  cache: *cache
  queue: *queue

test:
  primary: *primary
  cache: *cache
  queue: *queue

staging:
  primary: *primary
  cache: *cache
  queue: *queue

production:
  primary: *primary
  cache: *cache
  queue: *queue
```

### Steps to Reproduce
1. clone https://github.com/adrienpoly/rubyvideo
2. bundle install
3. comment what is inside the seed.rb for faster feedback
4. rails db:prepare
you should get a message Failed to clear Avo HQ response: Could not find table 'solid_cache_entries'

### System configuration
**Avo version**:

**Rails version**:
Rails 8

**Ruby version**:
3.3.5

**License type**:

 - [X] Community
 - [ ] Pro
 - [ ] Advanced

#### Impact

 - [x] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)
