### ISSUE TITLE
Fix `avo-rhino_field` styles

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#3527]
### Context

Installing `avo-rhino_field` plugin breaks the trix styles adding a margin arround the trix content:

![Image](https://github.com/user-attachments/assets/ecc51ac4-0294-4ca6-92f0-6cc91ea9914d)

This is caused because there is a conflict between [this import](https://github.com/avo-hq/avo/blob/main/app/assets/stylesheets/css/fields/trix.css#L1) and [this one](https://github.com/avo-hq/avo-rhino_field/blob/main/app/assets/stylesheets/avo-rhino_field.css#L1)

**Comment by Paul-Bob** [comment]
This border is added by [this line](https://github.com/avo-hq/avo-rhino_field/blob/main/app/assets/stylesheets/avo-rhino_field.css#L1) which is generating the following css class:

```css
.trix-content {
  border: 1px solid var(--rhino-border-color);
  border-radius: 0px 0px var(--rhino-border-radius) var(--rhino-border-radius);
  margin: 0;
  padding: 0.4em 0.6em;
  min-height: 200px;
  outline: transparent;
  overflow-wrap: break-word;
  word-break: break-word;
}

```
