### ISSUE TITLE
Fix actions dropdown disappearing with floating row controls

### ISSUE THREAD

**Issue by icaroryan** [avo-hq/avo#3867]
### Description

When using the `float: true` option in `row_controls_config`, the actions dropdown becomes unusable. The dropdown disappears as soon as the mouse leaves the table row to interact with the dropdown items, making it impossible to select any actions.

### Steps to use in the reproduction repository
1. Configure a resource with `float: true and show_on_hover:true` in row_controls_config:
```rb
# fish.rb
self.row_controls_config = {
  show_on_hover: true,
  float: true
}

self.row_controls = -> do
    actions_list
  end
```
2. View the resource index page
3. Click on the "Actions" dropdown button for any row
4. Try to move the mouse cursor to select an item in the dropdown

#### Expected behavior
The dropdown should remain visible when the mouse moves from the row to the dropdown, allowing users to select actions. It should only close when the mouse leaves the dropdown area or when clicking outside.

#### Observed behavior
The dropdown disappears as soon as the mouse cursor leaves the row and tries to enter the dropdown area, making it impossible to select any actions from the dropdown.

### System configuration
**Avo version**: 3.20.2

**License type**:

 - [ ] Community
 - [ ] Pro
 - [X] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [X] No

### Screenshots or screen recordings

https://www.loom.com/share/0fbc699ffd504187a3cedf4db7ccb339

In the first scenario, the `float` is turned off, and in the second one, I turned it on.

#### Impact

 - [X] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [X] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by icaroryan** [comment]
Another bug we might as well fix is the action dropdown showing up behind the other rows when `show_on_hover = false` but `float = true`

<img width="423" alt="Image" src="https://github.com/user-attachments/assets/6c9adbb1-d599-4562-880f-e795b9d21824" />

I believe this is because `floating-row-controls` adds a `z-index`, which is not the case for action dropdowns

**Comment by icaroryan** [comment]
After adding a lot of logic in `toggle_controller.js` handling hover events, I figured out a much simpler way to fix it only with a couple of lines of CSS.

```css
/* avo.base.css */

.floating-row-controls {
  &:before {
    content: "";
    @apply absolute z-10 inset-auto left-0 top-0 mt-0 -translate-x-full w-3 h-full bg-gradient-to-l from-white to-transparent group-hover:from-gray-50;
  }

  /* New code down bellow */
  &:hover,
  &:has([data-toggle-target="panel"]:hover) {
    @apply opacity-100 z-20;
  }
}
```
_"When someone hovers their mouse over the dropdown menu, make the row controls fully visible and make sure they appear on top of other elements on the page"_


This doesn't fix the panel showing up behind the other rows when `show_on_hover` is false. Still looking for a solution for it.

https://www.loom.com/share/e0797d93d05d42b2ae54dfa7cdbfc9cf

**Comment by Paul-Bob** [comment]
Hi @icaroryan, I really appreciate you taking the time to dig deep into this, thank you!

When we implemented `row_controls_config`, we didn’t notice this issue. It's definitely a bug and a styling problem, and I'm grateful you caught it and provided such a detailed report.

---

Watching your latest Loom, I noticed you already have a working solution for one of the problems, AWESOME work!

> It should only close when the mouse leaves the dropdown area or when clicking outside.

In my opinion, after opening the actions dropdown, the row controls and the dropdown itself should remain visible until the user clicks outside. Otherwise, the user has to be extremely careful not to accidentally move the mouse off the row or dropdown, which isn't ideal.

I'd like to hear your thoughts on this. Since you've already been exploring the issue, I'm also curious, do you think implementing this behavior would be difficult?

**Comment by icaroryan** [comment]
Hey @Paul-Bob!

I totally agree with your point. I think closing the dropdown action only when the user clicks away makes total sense and is more intuitive. 

To achieve that, we'd just have to tweak the CSS a bit to apply those properties only when the dropdown is active.

```css
.floating-row-controls {
  &:before {
    content: "";
    @apply absolute z-10 inset-auto left-0 top-0 mt-0 -translate-x-full w-3 h-full bg-gradient-to-l from-white to-transparent group-hover:from-gray-50;
  }

  &:hover,
  &:has([data-toggle-target="panel"]:not(.hidden)) {
    @apply opacity-100 z-20;
  }
}
```

There's still some weirdness when you hover over other rows, as it shows up in front of the dropdown, but I expect that to be gone once we fix the second problem.

https://www.loom.com/share/778daa5d221244a78589d1e6fbf3e96f

A propósito, do you have any ideas on how to fix the overlay problem?
